frequency: 30
sensor_timeout: 0.1
two_d_mode: false
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map
debug: false

imu0: 
  update: true
  sensor_type: imu
  imu_frame_id: imu_link
  base_link_frame_id: base_link
  topic: /imu/data_raw
  acceleration_limits: [8.0, 8.0, 3.0]
  angular_velocity_limits: [2.5, 2.5, 1.0]
  orientation_cutoff: 1.0

imu0_config: [false, false, false,
              true,  true,  true,
              false, false, false,
              true,  true,  true,
              true,  true,  true]
              
odom0:
  update: true
  sensor_type: odometry
  odom_frame_id: odom
  base_link_frame_id: base_link
  topic: /odom
  differential: false
  pose_rejection_threshold: 2.0
  twist_rejection_threshold: 1.0

odom0_config: [true,  true,  false,
               false, false, false,
               false, false, false,
               false, false, true,
               false, false, false]

scan0:
  update: true
  sensor_type: laser
  frame_id: lidar_link
  base_link_frame_id: base_link
  topic: /scan
  covariance_diagonal: [0.1, 0.1, 0.2, 0.2, 0.2]

